package field

const (
	ID                  Field = "id"
	JobID               Field = "jid"
	TaskID              Field = "tid"
	ClientID            Field = "cid"
	Tags                Field = "tags"
	ADDR                Field = "addr"
	Method              Field = "method"
	NameLookUpTime      Field = "name_lookup_time"
	ConnectTime         Field = "connect_time"
	AppConnectTime      Field = "app_connect_time"
	TCPTime             Field = "tcp_time"
	SSLTime             Field = "ssl_time"
	PreTransferTime     Field = "pre_transfer_time"
	TTFB                Field = "ttfb"
	ServerProcessTime   Field = "server_process_time"
	StartTransferTime   Field = "start_transfer_time"
	ContentTransferTime Field = "content_transfer_time"
	TotalTime           Field = "total_time"
	ConnectedVia        Field = "connected_via"
	Headers             Field = "headers"
	Body                Field = "body"
	Status              Field = "status"
	StatusCode          Field = "status_code"
	Sent                Field = "sent"
	Recv                Field = "recv"
	LossPct             Field = "loss_pct"
	StdDevTotalTime     Field = "stddev_total_time"
)
